### ISSUE TITLE
duplicate tablet_socket_msgs package with autoware/messages

### ISSUE THREAD

**Issue by mitsudome-r** [autowarefoundation/utilities#2]
### Required information:

- Operating system and version:
  - Ubuntu 16.04 
- Autoware installation type:
  - From source
- Autoware version or commit hash
  - autoware.repos file in autowarefoundation/autoware repository(master branch)

- ROS distribution and version:
  - ROS kinetic
- ROS installation type:
  - from binary
- Package or library, if applicable:
  - tablet_socket_msgs

### Description of the bug

There is table_socket_msgs package in this repository and messages repository.
This gives error when building source from autoware.repos file

colcon build gives the following error when running `colcon build --cmake-args -DCMAKE_BUILD_TYPE=Release`
```
ERROR:colcon:colcon build: Duplicate package names not supported:
- tablet_socket_msgs:
  - /home/mitsudome-r/autoware_colcon_ws/src/autoware/messages/tablet_socket_msgs
  - /home/mitsudome-r/autoware_colcon_ws/src/autoware/utilities/tablet_socket_msgs
```

### Steps to reproduce the bug
1. mkdir -p colcon_ws/src/autoware
1. cd colcon_ws/src/autoware
1. git clone https://github.com/autowarefoundation/autoware.git
1. cd ../
1. vcs import < autoware/autoware/autoware.repos
1. remove duplicate packages in autoware/autoware 
`for f in $(colcon build --cmake-args -DCMAKE_BUILD_TYPE=Release 2>&1 | grep autoware/autoware/ros/src | sed -e 's/  - //g'); do rm $f -r;done`
1. colcon build --cmake-args -DCMAKE_BUILD_TYPE=Release

### Expected behavior

colcon builds successfully

### Actual behavior

colcon build fails due to duplicate package tablet_socket_msgs

**Comment by gbiggs** [comment]
Fixed by https://github.com/autowarefoundation/utilities/pull/1
